### ISSUE TITLE
Gulpfile plugins

### ISSUE THREAD

**Issue by eko24ive** [Artinov/home-work-7-kramarmm#1]
Consider using `gulp-load-plugins` to reduce plugin import and declaration: https://github.com/jackfranklin/gulp-load-plugins

**Comment by kramarmm** [comment]
Fixed
https://github.com/Artinov/home-work-7-kramarmm/commit/af0dd1f13d504b2ab157d8d5b7c60546d09c8bba#diff-b9e12334e9eafd8341a6107dd98510c9

**Comment by eko24ive** [comment]
Awesome !
