### ISSUE TITLE
Contact form size

### ISSUE THREAD

**Issue by eko24ive** [Artinov/home-work-7-kramarmm#10]
Your contact form is too big:
![image](https://cloud.githubusercontent.com/assets/25591824/23082751/6163efe6-f563-11e6-9358-7034d661c933.png)

Compare it to design:
![image](https://cloud.githubusercontent.com/assets/25591824/23082768/7020e58e-f563-11e6-844a-96dba67172f7.png)

**Comment by kramarmm** [comment]
Fixed

**Comment by eko24ive** [comment]
Good !
