### ISSUE TITLE
Using !important

### ISSUE THREAD

**Issue by eko24ive** [Artinov/home-work-7-kramarmm#4]
Using `!important` in CSS is bad approach.
You can control the order of css-files you load on your page.
For example:
```html
<link rel="stylesheet" type="text/css" href="./A.css">
<link rel="stylesheet" type="text/css" href="./B.css">
<link rel="stylesheet" type="text/css" href="./C.css">
```

This means, that file A is loaded first.
Then goes file B.
And finally C.

But remember, that each next css file overrides rules for same selectors in previous file, for example
C overrides B, B overrides A

Here is handy scheme of file priority:
C > B > A

Keep this in mind, and make order of your files the way it'll reduce usage of `!important`.
### Of course there are some situations when usage of `!important` is really necessary, but this cases are extremely rare !

**Comment by kramarmm** [comment]
Fixed

**Comment by eko24ive** [comment]
Nicely done !
