### ISSUE TITLE
Variable naming in SASS

### ISSUE THREAD

**Issue by eko24ive** [Artinov/home-work-7-kramarmm#5]
Naming variable like explicitly could bring specific consequences in some time.
E.g.
```sass
$greyColor: #333333
```

Yes, color of this variable is gray. You are using this variable three times.
But what if you're used this variable fifty times, and I wanted you to change color from `#333333` to `skyblue`.
You could simply change `$greyColor` value, but name of variable isn't referencing to gray color anymore. And you're code became slightly confusing. And you can fix it by changing variable name. Everywhere. Fifty times. Not good, isn't it ?)

It would be better if name of your variable would be more abstract.
For example, `navigationColor` or `primaryColor`. In this case you can freely and fearless change it's value. And your code remains valid.

**Comment by kramarmm** [comment]
Fixed

**Comment by eko24ive** [comment]
Great !
