### ISSUE TITLE
Start side lines width

### ISSUE THREAD

**Issue by eko24ive** [Artinov/home-work-7-kramarmm#9]
Length of right and left line is differs.

![image](https://cloud.githubusercontent.com/assets/25591824/23082666/0461d8a8-f563-11e6-8686-fcdde92bfd80.png)
![image](https://cloud.githubusercontent.com/assets/25591824/23082696/2929aa6c-f563-11e6-98bd-f215657fc87a.png)
![image](https://cloud.githubusercontent.com/assets/25591824/23082715/347f075e-f563-11e6-8a75-c2d835f0fc0f.png)
![image](https://cloud.githubusercontent.com/assets/25591824/23082725/3db3e560-f563-11e6-80ae-54f4da506b37.png)

**Comment by kramarmm** [comment]
Fixed

**Comment by kramarmm** [comment]
Fixed

**Comment by eko24ive** [comment]
Nice !
